# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: ad217d6
_src_path: git@github.com:Honekatsu/skills-template.git
create_new_skill: false
include_common_tools: false
include_design_authority: false
include_embedded_development_guidelines: false
include_git_workflow: true
include_japanese_tech_writing: false
include_skill_editing_guidelines: false
include_technical_document_writing: false
overwrite_existing_skills: true
